# Generated by Django 5.1.6 on 2025-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
    ]
