# Generated by Django 5.1.6 on 2025-03-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="senha",
        ),
    ]
