# Generated by Django 5.1.6 on 2025-03-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_remove_myuser_senha"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyUser",
        ),
    ]
