# Generated by Django 5.1.6 on 2025-03-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cursos",
            name="nome",
        ),
        migrations.AddField(
            model_name="cursos",
            name="curso",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="cursos",
            name="faculdade",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="cursos",
            name="numero_vagas",
            field=models.IntegerField(default=0),
        ),
    ]
