# Generated by Django 5.1.6 on 2025-03-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_cursos_nome_cursos_curso_cursos_faculdade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursos",
            name="curso",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="cursos",
            name="faculdade",
            field=models.CharField(default="", max_length=200),
        ),
    ]
